sonar.projectKey=jjoaom_TI4-ANIMONGS
sonar.organization=jjoaom

sonar.sources=frontend/lib,backend/src/main/kotlin
sonar.tests=frontend/test,backend/src/test/kotlin

sonar.exclusions=\
**/build/**,\
**/.dart_tool/**,\
**/node_modules/**,\
**/.gradle/**,\
**/target/**,\
**/generated/**,\
**/*.g.dart,\
**/*.freezed.dart,\
**/*.gr.dart,\
**/docs/**,\
frontend/android/**,\
frontend/ios/**,\
frontend/linux/**,\
frontend/macos/**,\
frontend/windows/**,\
frontend/web/**

sonar.coverage.exclusions=\
**/config/**,\
**/dto/**,\
**/model/**,\
**/generated/**,\
**/*.g.dart,\
**/*.freezed.dart

sonar.sourceEncoding=UTF-8