# identificação do projeto
sonar.projectKey=jjoaom_TI4-ANIMONGS
sonar.organization=jjoaom

# somente código relevante
sonar.sources=frontend,backend,scripts,db

# diretórios de testes
sonar.tests=front/test,back/src/test

# exclusões globais
sonar.exclusions=\
**/build/**,\
**/.dart_tool/**,\
**/node_modules/**,\
**/.gradle/**,\
**/target/**,\
**/generated/**,\
**/*.g.dart,\
**/*.freezed.dart,\
**/*.gr.dart,\
**/docs/**,\
**/scripts/**

# exclusões de cobertura
sonar.coverage.exclusions=\
**/config/**,\
**/dto/**,\
**/model/**,\
**/generated/**,\
**/*.g.dart,\
**/*.freezed.dart

# encoding padrão
sonar.sourceEncoding=UTF-8