name: Qodana - Frontend
on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'frontend/**'
  push:
    branches:
      - main
      - 'releases/*'
    paths:
      - 'frontend/**'

jobs:
  qodana-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Generate local.properties
        run: |
          echo "sdk.dir=/opt/android-sdk" > frontend/android/local.properties
          echo "flutter.sdk=$FLUTTER_ROOT" >> frontend/android/local.properties

      - name: Qodana Scan - Frontend Flutter
        uses: JetBrains/qodana-action@v2025.3
        with:
          pr-mode: false
          args: -i,frontend/android,--image,jetbrains/qodana-jvm-android:2025.3
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_1255759463 }}
          QODANA_ENDPOINT: "https://qodana.cloud"
