name: Qodana - Backend
on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'backend/**'
  push:
    branches:
      - main
      - 'releases/*'
    paths:
      - 'backend/**'

jobs:
  qodana-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Qodana Scan - Backend Kotlin
        uses: JetBrains/qodana-action@v2025.3
        with:
          pr-mode: false
          args: -i,backend
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_662540184 }}
          QODANA_ENDPOINT: 'https://qodana.cloud'