name: Qodana - Backend
on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'frontend/**'
  push:
    branches:
      - main
      - 'releases/*'
    paths:
      - 'frontend/**'
jobs:
  qodana-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Qodana Scan - Frontend Flutter
        uses: JetBrains/qodana-action@v2025.3
        with:
          pr-mode: false
          use-caches: true
          linter: qodana-jvm-android
          project-dir: frontend
          within-docker: true
          cache-dir: .qodana/cache
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_1255759463 }}
          QODANA_ENDPOINT: 'https://qodana.cloud'