name: Qodana

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:

  qodana-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Qodana Backend (JVM)
        uses: JetBrains/qodana-action@v2025.3
        with:
          linter: jetbrains/qodana-jvm
          project-dir: backend
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_988999275 }}
          QODANA_ENDPOINT: 'https://qodana.cloud'


  qodana-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Qodana Frontend (Flutter)
        uses: JetBrains/qodana-action@v2025.3
        with:
          linter: jetbrains/qodana-flutter
          project-dir: frontend
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_988999275 }}
          QODANA_ENDPOINT: 'https://qodana.cloud'
