name: trivy

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: '33 0 * * 0'

permissions:
  contents: read

jobs:
  scan-backend:
    name: Build and scan backend image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build backend image
        run: |
          docker build \
            -t my-app-backend:${{ github.sha }} \
            -f backend/Dockerfile backend

      - name: Scan backend image
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: 'my-app-backend:${{ github.sha }}'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-backend-results.sarif'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true
          trivyignores: .trivyignore

      - name: Upload backend scan results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-backend-results.sarif'

  scan-db:
    name: Build and scan DB image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build DB image
        run: |
          docker build \
            -t my-app-db:${{ github.sha }} \
            -f db/Dockerfile db

      - name: Scan DB image
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: 'my-app-db:${{ github.sha }}'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-db-results.sarif'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true
          trivyignores: .trivyignore

      - name: Upload DB scan results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-db-results.sarif'