name: trivy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: '33 0 * * 0'

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read
      security-events: write
      actions: read
    name: Build and scan images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build all images
        run: |
          docker-compose -f scripts/docker-compose.dev.yml build

      - name: Scan backend image
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: 'docker.io/my-organization/my-app-backend:${{ github.sha }}'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-backend-results.sarif'
          severity: 'CRITICAL,HIGH'
      - name: Scan DB image
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: 'docker.io/my-organization/my-app-db:${{ github.sha }}'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-db-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload backend scan results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-backend-results.sarif'

      - name: Upload DB scan results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-db-results.sarif'
